language: go

go:
  - 1.8
  - 1.9

install:
  - go get go.uber.org/zap
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/onsi/gomega
  - go get github.com/golang/lint/golint

script:
  - go test -v
  - ginkgo -v
  - go vet
  - golint
