name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19

      - name: Set up ginkgo
        run: go get github.com/onsi/ginkgo/ginkgo

      - name: Test
        run:
          - go test -v
          - ginkgo -v
